# Generated by Django 5.1.15 on 2026-08-15 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0003_communitymember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("github_repo_url", models.TextField(blank=True, null=True)),
                ("blog_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="communities.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["community", "created_at"],
                        name="posts_communi_23a985_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="posts_user_id_6b02c5_idx"
                    ),
                ],
            },
        ),
    ]
