# Generated by Django 5.1.15 on 2026-08-08 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryLanguage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("language", models.CharField(max_length=100)),
                (
                    "bytes",
                    models.BigIntegerField(
                        help_text="Bytes of code written in this language"
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of the repository written in this language",
                        max_digits=5,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        db_column="repository_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "db_table": "repository_languages",
                "ordering": ["-percentage"],
                "unique_together": {("repository", "language")},
            },
        ),
    ]
