# Generated by Django 5.1.15 on 2026-08-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_first_name_remove_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["github_username"], name="users_user_github__c7d60f_idx"
            ),
        ),
    ]
