# Generated by Django 5.1.15 on 2026-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="language",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Primary programming language for this community",
                max_length=100,
                null=True,
            ),
        ),
    ]
