# Generated by Django 5.1.15 on 2026-08-14 02:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_community_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="communities.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Member",
                "verbose_name_plural": "Community Members",
                "db_table": "community_members",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["community", "role"],
                        name="community_m_communi_77a31a_idx",
                    ),
                    models.Index(
                        fields=["user"], name="community_m_user_id_0554b5_idx"
                    ),
                ],
                "unique_together": {("community", "user")},
            },
        ),
    ]
