# Generated by Django 5.1.15 on 2026-08-09 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("watchers", models.IntegerField(default=0)),
                ("open_issues", models.IntegerField(default=0)),
                ("subscribers", models.IntegerField(default=0)),
                ("network", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0)),
                ("default_branch", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="repositories.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["repository", "collected_at"],
                        name="analytics_r_reposit_820fbb_idx",
                    ),
                    models.Index(
                        fields=["user", "collected_at"],
                        name="analytics_r_user_id_cc0f81_idx",
                    ),
                ],
                "unique_together": {("repository", "collected_at")},
            },
        ),
        migrations.CreateModel(
            name="UpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("SCHEDULED", "Scheduled"),
                            ("WEBHOOK", "Webhook"),
                            ("INITIAL", "Initial"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("repositories_updated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_logs",
                        to="repositories.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="analytics_u_user_id_cb49fb_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="analytics_u_started_c120b1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_repos", models.IntegerField(default=0)),
                ("total_stars", models.IntegerField(default=0)),
                ("total_forks", models.IntegerField(default=0)),
                ("total_watchers", models.IntegerField(default=0)),
                ("total_open_issues", models.IntegerField(default=0)),
                ("public_repos", models.IntegerField(default=0)),
                ("private_repos", models.IntegerField(default=0)),
                ("followers", models.IntegerField(default=0)),
                ("following", models.IntegerField(default=0)),
                ("contributions", models.IntegerField(default=0)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "collected_at"],
                        name="analytics_u_user_id_f5443f_idx",
                    )
                ],
                "unique_together": {("user", "collected_at")},
            },
        ),
    ]
