# Generated by Django 5.1.15 on 2026-08-09 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("repositories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.BigIntegerField(unique=True)),
                ("login", models.CharField(max_length=255)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("html_url", models.URLField(blank=True, max_length=500, null=True)),
                ("contributions", models.IntegerField(default=0)),
                ("first_contribution_at", models.DateTimeField(blank=True, null=True)),
                ("last_contribution_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="repositories.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-contributions"],
            },
        ),
        migrations.CreateModel(
            name="ContributorLanguages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                ("bytes", models.BigIntegerField(default=0)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="analytics.contributor",
                    ),
                ),
            ],
            options={
                "ordering": ["-bytes"],
            },
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(
                fields=["repository", "contributions"],
                name="analytics_c_reposit_8b24bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(
                fields=["user", "login"], name="analytics_c_user_id_0db053_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("repository", "github_id")},
        ),
        migrations.AddIndex(
            model_name="contributorlanguages",
            index=models.Index(
                fields=["contributor", "bytes"], name="analytics_c_contrib_f459d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contributorlanguages",
            index=models.Index(
                fields=["language"], name="analytics_c_languag_e5246f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contributorlanguages",
            unique_together={("contributor", "language")},
        ),
    ]
