# Generated by Django 5.1.15 on 2026-08-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_contributor_contributorlanguages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="github_id",
            field=models.BigIntegerField(),
        ),
    ]
