# Generated by Django 5.1.15 on 2026-08-10 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_contributor_github_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributorActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("commits", models.IntegerField(default=0)),
                ("pull_requests", models.IntegerField(default=0)),
                ("reviews", models.IntegerField(default=0)),
                ("issues", models.IntegerField(default=0)),
                ("additions", models.BigIntegerField(default=0)),
                ("deletions", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository_contributor",
                    models.ForeignKey(
                        db_column="repository_contributor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="analytics.contributor",
                    ),
                ),
            ],
            options={
                "db_table": "contributor_activity",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["repository_contributor", "period_start"],
                        name="contributor_reposit_95e1d2_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="contributor_period__583a11_idx",
                    ),
                ],
                "unique_together": {
                    ("repository_contributor", "period_start", "period_end")
                },
            },
        ),
    ]
