# Generated by Django 5.1.15 on 2026-08-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_contributoractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="recent_commits",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
