# Generated by Django 5.1.15 on 2026-08-15 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadmeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("thumbnail", models.TextField(blank=True, null=True)),
                ("markdown_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "readme_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReadmeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        default="",
                        help_text="Markdown content with placeholders like {{user.name}}, {{stats.total_stars}}, etc.",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("minimal", "Minimal"),
                            ("dark", "Dark Theme"),
                            ("visual", "Visual Heavy"),
                            ("professional", "Professional"),
                        ],
                        default="modern",
                        max_length=50,
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("auto_update_enabled", models.BooleanField(default=True)),
                (
                    "update_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("daily", "Daily"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("next_update", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("export_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readme_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "README Profile",
                "verbose_name_plural": "README Profiles",
                "db_table": "readme_profiles",
            },
        ),
        migrations.CreateModel(
            name="ReadmeGenerationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("in_progress", "In Progress"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("content_length", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_history",
                        to="readme_profiles.readmeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "readme_generation_history",
                "ordering": ["-generated_at"],
            },
        ),
    ]
