# Generated by Django 5.1.15 on 2026-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readme_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="readmeprofile",
            name="generated_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Last fully-resolved output (placeholders filled in, badges/chart injected). This is what gets displayed/exported - `content` above stays as the raw editable template and is never overwritten by generation.",
            ),
        ),
    ]
