# Generated by Django 5.1.15 on 2026-08-07 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("github_repo_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "primary_language",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("default_branch", models.CharField(default="main", max_length=100)),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("watchers", models.IntegerField(default=0)),
                ("open_issues", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0)),
                ("license", models.CharField(blank=True, max_length=100, null=True)),
                ("homepage", models.URLField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("created_at_github", models.DateTimeField()),
                ("updated_at_github", models.DateTimeField()),
                ("pushed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "repositories",
                "ordering": ["-created_at_github"],
                "indexes": [
                    models.Index(
                        fields=["user", "github_repo_id"],
                        name="repositorie_user_id_9e006b_idx",
                    ),
                    models.Index(
                        fields=["user", "-stars"], name="repositorie_user_id_ada3df_idx"
                    ),
                    models.Index(
                        fields=["visibility"], name="repositorie_visibil_39838b_idx"
                    ),
                    models.Index(
                        fields=["primary_language"],
                        name="repositorie_primary_82c1e2_idx",
                    ),
                    models.Index(
                        fields=["archived"], name="repositorie_archive_7edd39_idx"
                    ),
                ],
            },
        ),
    ]
