# Generated by Django 5.1.15 on 2026-08-11 02:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Web", "Web"),
                            ("Mobile", "Mobile"),
                            ("Desktop", "Desktop"),
                            ("AI", "AI"),
                            ("API", "API"),
                            ("CLI", "CLI"),
                            ("IoT", "IoT"),
                            ("Game", "Game"),
                            ("Library", "Library"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence score from 0.00 to 100.00",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_categories",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "db_table": "project_categories",
                "ordering": ["-confidence"],
                "indexes": [
                    models.Index(
                        fields=["repository", "category"],
                        name="project_cat_reposit_c8b4a4_idx",
                    ),
                    models.Index(
                        fields=["category", "confidence"],
                        name="project_cat_categor_1ab46d_idx",
                    ),
                ],
                "unique_together": {("repository", "category")},
            },
        ),
    ]
